services:
  scheduler:
    image: mageai/mageai
    volumes:
      - "./scheduler_data:/home/src" 
    ports:
      - "6789:6789" # Puerto de mageai
    command: /app/run_app.sh mage start scheduler # Comando para iniciar el scheduler de mageai
    